from setuptools import setup, find_packages

setup(name='mogptk',
      version='0.1',
      description='Multi-Output Gaussian Process ToolKit',
      url='https://github.com/GAMES-UChile/MultiOutputGP-Toolbox',
      author='Taco de Wolff, Alejandro Cuevas, Felipe Tobar',
      author_email='tacodewolff@gmail.com',
      license='MIT',
      packages=find_packages(exclude=['examples']),
      include_package_data=False,
      keywords=['MOGP', 'MOSM', 'GP', 'Gaussian Process', 'Multi-Output', 'Tobar', 'Parra'],
      python_requires='~=3.7.0',
      install_requires=[
          'numpy~=1.18.0',
          'gpflow~=2.0.0rc1',
          'tensorflow~=2.0.0',
          'tensorflow-probability~=0.8.0',
          'matplotlib',
          'scipy',
          'scikit-learn',
          'pandas',
          'seaborn',
          'python-dateutil',
          'ipython',
      ],
)
